FROM debian:buster
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y php php-fpm curl less wget zip systemd php-mysql php-mysqli
# RUN apt-get install -y mariadb-client
RUN wget https://github.com/WordPress/WordPress/archive/refs/tags/6.2.2.zip 
# RUN	curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
# &&		chmod +x wp-cli.phar \
# &&		mv wp-cli.phar /usr/local/bin/wp
RUN  unzip 6.2.2.zip
RUN mv WordPress-6.2.2 wordpress
RUN mkdir -p /var/www/wordpress
RUN cp -rf ./wordpress/*  /var/www/wordpress

RUN rm -rf /etc/php/7.3/fpm/pool.d/www.conf

COPY www.conf /etc/php/7.3/fpm/pool.d/

RUN mkdir -p /run/php/

# WORKDIR /var/www/wordpress
# RUN wp core config --dbhost=mariadb --dbname=wordpress --dbuser=wordpress --dbpass=123456 --allow-root --skip-check
# RUN chmod 600 wp-config.php
EXPOSE 	9000
CMD [ "php-fpm7.3", "-F" ]

