FROM debian:buster
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install nginx
RUN apt-get install -y openssl
COPY .conf /etc/nginx/sites-available/.conf
EXPOSE 443
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]