FROM debian:buster
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install nginx curl less
RUN apt-get install -y openssl
COPY wordpress.conf /etc/nginx/sites-available/default
EXPOSE 80
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]